[package]
name = "einerleih"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { version = "0.5.3", features = ["std"] }
async-trait = "0.1.89"
axum = { version = "0.8.8", features = ["json", "multipart"] }
axum-macros = "0.5.0"
chrono = "0.4.44"
config = "0.15.22"
deadpool-postgres = { version = "0.14.1", features = ["serde"] }
dotenvy = "0.15.7"
getrandom = { version = "0.4.2", features = ["sys_rng"] }
http-body-util = "0.1.3"
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
once_cell = "1.21.4"
rand = "0.10.0"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
simple_dto_mapper_derive = "0.1.1"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["rt-multi-thread", "macros", "signal"] }
tokio-postgres = { version = "0.7.17", features = ["with-uuid-1", "with-chrono-0_4"] }
tower = { version = "0.5.3", features = ["timeout", "util"] }
tower-http = { version = "0.6.8", features = ["cors", "fs", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "registry", "std", "fmt", "chrono"] }
utoipa = { version = "5.4.0", features = ["axum_extras", "uuid", "chrono"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
uuid = { version = "1.23.0", features = ["serde", "v4"] }
validator = { version = "0.20.0", features = ["derive"] }
